---

- name: Download and extract MYSQL connector
  unarchive: src="{{ mysql_connector_url }}" dest={{ system_tmp }} owner={{ confluence_user }} group={{ confluence_user }} copy=no

- name: Copy the connector into jira libs directory
  command: "cp {{ system_tmp }}/mysql-connector-java-{{ mysql_connector_version }}/mysql-connector-java-{{ mysql_connector_version }}-bin.jar {{ confluence_installatie_directory }}/{{ confluence_installatie_versie }}/lib"

- name: Create default database user for application
  mysql_user: name={{ db_application_user }} 
              password={{ db_application_password }} 
              login_host={{ db_hostname }}
              login_port={{ db_port }}
              login_user={{ db_admin_user }} 
              login_password={{ db_admin_password }} 
              priv=*.*:ALL,GRANT 
              state=present

- name: Create default database
  mysql_db: name={{ db_name }} 
            login_host={{ db_hostname }}
            login_port={{ db_port }}
            login_user={{ db_admin_user }} 
            login_password={{ db_admin_password }} 
            encoding=utf8
            collation=utf8_bin
            state=present
